package blockchain

// ============================ Proof of Work ============================

// ProofOfWork algorithm used in mining blocks
type ProofOfWork struct {
	nonce int
}

// ProofMethod is the interface method that calls this component's proof method
func (p ProofOfWork) ProofMethod() {
	proofOfWork()
}

// ValidateProof verifies that the proof generated by this component's proof method is a valid proof
func (p ProofOfWork) ValidateProof() {

}

// proofOfWork is the proof of work algorithm that
func proofOfWork() int {
	return 0
}
